#!/usr/bin/env python3
"""Normalize legacy personal GitHub origins in a finished internal package."""

from __future__ import annotations

import argparse
import json
import os
import stat
import sys
import tempfile
from pathlib import Path


LEGACY_NAMESPACE = "https://github.com/matthiasrohr/"
LEGACY_RAW_NAMESPACE = "https://raw.githubusercontent.com/matthiasrohr/"
ORGANIZATION_NAMESPACE = "https://github.com/appsec-foundry/"
ORGANIZATION_RAW_NAMESPACE = "https://raw.githubusercontent.com/appsec-foundry/"

# Only repositories whose appsec-foundry destinations are known to exist may be
# rewritten. An unexpected personal link fails the package instead of silently
# producing a plausible-looking 404 URL.
REPOSITORIES = (
    "ai-secure-coding-baseline",
    "appsec-advisor-packaging-template",
    "appsec-advisor-fixtures",
    "appsec-advisor-examples",
    "appsec-advisor",
)
REPLACEMENTS = tuple(
    (
        f"{LEGACY_NAMESPACE}{repository}",
        f"{ORGANIZATION_NAMESPACE}{repository}",
    )
    for repository in REPOSITORIES
) + (
    (
        f"{LEGACY_RAW_NAMESPACE}ai-secure-coding-baseline",
        f"{ORGANIZATION_RAW_NAMESPACE}ai-secure-coding-baseline",
    ),
)
CONFIGURATION_HELP = (
    "Generated runtime configuration; do not edit this file. Configure organization "
    "identity, presets, requirements, policy, banner, baseline, context, security "
    "coach, actors, abuse cases, skill_toggles, hooks, and MCP in "
    "org-profile/org-profile.yaml and its referenced files; configure the internal "
    "help/README link as INTERNAL_REPOSITORY_URL in the Makefile. Select packaged skills, "
    "hooks, and MCP servers in org-profile/package-policy.yaml; inspect the resolved "
    "surface in .claude-plugin/package-surface.json. See "
    "README.md#configuration-map."
)


class RewriteError(ValueError):
    """The packaged tree cannot be rewritten safely."""


def _write_atomic(path: Path, text: str) -> None:
    mode = stat.S_IMODE(path.stat().st_mode)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", dir=path.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(text)
        os.chmod(temporary, mode)
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def rewrite(plugin_root: Path) -> int:
    config_path = plugin_root / "config.json"
    if not config_path.is_file():
        raise RewriteError(f"required file is missing: {config_path}")

    updates: list[tuple[Path, str]] = []
    unexpected: list[str] = []
    needles = (LEGACY_NAMESPACE.encode(), LEGACY_RAW_NAMESPACE.encode())

    for path in sorted(plugin_root.rglob("*")):
        if path.is_symlink():
            raise RewriteError(f"refusing to inspect packaged symlink: {path}")
        if not path.is_file():
            continue
        try:
            raw = path.read_bytes()
        except OSError as exc:
            raise RewriteError(f"cannot read packaged file {path}: {exc}") from exc
        if not any(needle in raw for needle in needles):
            continue
        try:
            text = raw.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise RewriteError(
                f"legacy GitHub origin appears in non-UTF-8 file {path}"
            ) from exc

        updated = text
        for old, new in REPLACEMENTS:
            updated = updated.replace(old, new)
        if LEGACY_NAMESPACE in updated or LEGACY_RAW_NAMESPACE in updated:
            unexpected.append(str(path.relative_to(plugin_root)))
        elif updated != text:
            updates.append((path, updated))

    if unexpected:
        files = ", ".join(unexpected[:10])
        raise RewriteError(
            "packaged files contain unmapped personal GitHub origins; add only "
            f"verified appsec-foundry destinations before packaging: {files}"
        )

    updates_by_path = dict(updates)
    try:
        config_text = updates_by_path.get(config_path)
        if config_text is None:
            config_text = config_path.read_text(encoding="utf-8")
        config = json.loads(config_text)
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise RewriteError(f"cannot read packaged config {config_path}: {exc}") from exc
    if not isinstance(config, dict):
        raise RewriteError(f"packaged config must be a JSON object: {config_path}")
    config["_comment"] = CONFIGURATION_HELP
    updates_by_path[config_path] = json.dumps(config, indent=2, ensure_ascii=False) + "\n"

    for path, updated in updates_by_path.items():
        _write_atomic(path, updated)
    return len(updates)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Replace verified legacy GitHub origins in a packaged plugin."
    )
    parser.add_argument("--plugin-root", required=True, type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        changed = rewrite(args.plugin_root.resolve())
    except RewriteError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    if changed:
        print(f"Repository origins normalized in {changed} packaged file(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
